Repository CA-G12/NewsPage-Ibtisam-Tareq, pull requests merged in 2022-08, with the labels that each got.

#3 Adding file structure
  .gitignore
  package-lock.json
  package.json
  public/CSS/style.css
  public/JS/dom.js
  public/JS/script.js
  public/index.html
  src/app.js
  src/handlers.js
  src/index.js
  tests/project.test.js
Labels: Approved

#5 add SRC to do the back end ( controller and error and server and router files )
  public/JS/script.js
  public/index.html
  src/app.js
  src/controllers/errors/client-error.js
  src/controllers/errors/index.js
  src/controllers/errors/server-error.js
  src/controllers/index.js
  src/controllers/landing-page/get-landing-page.js
  src/controllers/landing-page/get-news.js
  src/controllers/landing-page/index.js
  src/handlers.js
  src/index.js
  src/router.js
  src/server.js
Labels: Approved

#6 Adding Styled Home Page and error pages and linking them to the server
  package-lock.json
  package.json
  public/CSS/style.css
  public/assets/error.png
  public/assets/news-icon.png
  public/assets/news-logo.png
  public/errors/404.html
  public/errors/500.html
  public/index.html
  src/app.js
  src/controllers/errors/client-error.js
  src/controllers/errors/server-error.js
  src/controllers/index.js
  src/controllers/landing-page/get-news.js
  src/router.js
  src/server.js
Labels: Approved

#8 Fetching News and rendering them in the front end
  public/CSS/style.css
  public/JS/script.js
  src/controllers/landing-page/get-news.js
Labels: Approved

#12 9 building news card
  public/JS/script.js
  public/assets/loading.jpg
Labels: Approved

#14 update style in css and add some element to dom
  public/CSS/style.css
  public/JS/script.js
  public/assets/loading.jpg
  public/index.html
Labels: Approved

#17 edit heroku bugs
  package.json
Labels: Approved

#16 10 search functionality
  public/CSS/style.css
  public/JS/script.js
  public/index.html
  src/controllers/index.js
  src/controllers/landing-page/get-news.js
  src/controllers/landing-page/index.js
  src/controllers/landing-page/search-news.js
  src/router.js
  tests/project.test.js
Labels: Approved

#18 Testing Routes Passed successfully
  tests/project.test.js
Labels: Approved

#21 Editing Live link in readme file
  README.md
  package-lock.json
  package.json
Labels: Awaiting Review

#22 Fixing bugs
  public/CSS/style.css
  public/JS/script.js
  src/app.js
  src/controllers/landing-page/get-news.js
  src/controllers/landing-page/search-news.js
Labels: Approved

#23 Fixing tests
  public/CSS/style.css
  src/controllers/errors/client-error.js
  src/controllers/errors/server-error.js
  tests/project.test.js
Labels: Done

#24 Refactoring
  public/CSS/style.css
  public/JS/script.js
  public/index.html
Labels: Approved

#25 Refactoring code and updating style
  public/CSS/style.css
  public/JS/dom.js
  public/JS/script.js
  public/assets/logo.png
  public/assets/news-icon.png
  public/index.html
  src/controllers/landing-page/get-news.js
  src/controllers/landing-page/search-news.js
  tests/project.test.js
Labels: Done
